/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const WithdrawalRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'paymentMethod' : IDL.Text,
  'username' : IDL.Text,
  'bankAccount' : IDL.Text,
  'bankHolderName' : IDL.Text,
  'upiQrUrl' : IDL.Text,
  'uploadedQrBase64' : IDL.Text,
  'fullName' : IDL.Text,
  'payoutRupees' : IDL.Float64,
  'bankIfsc' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'timestamp' : IDL.Int,
  'upiId' : IDL.Text,
  'phone' : IDL.Text,
  'points' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getAllWithdrawals' : IDL.Func([], [IDL.Vec(WithdrawalRequest)], ['query']),
  'submitWithdrawal' : IDL.Func([WithdrawalRequest], [IDL.Nat], []),
  'updateWithdrawalStatus' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const WithdrawalRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'paymentMethod' : IDL.Text,
    'username' : IDL.Text,
    'bankAccount' : IDL.Text,
    'bankHolderName' : IDL.Text,
    'upiQrUrl' : IDL.Text,
    'uploadedQrBase64' : IDL.Text,
    'fullName' : IDL.Text,
    'payoutRupees' : IDL.Float64,
    'bankIfsc' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'timestamp' : IDL.Int,
    'upiId' : IDL.Text,
    'phone' : IDL.Text,
    'points' : IDL.Nat,
  });
  
  return IDL.Service({
    'getAllWithdrawals' : IDL.Func([], [IDL.Vec(WithdrawalRequest)], ['query']),
    'submitWithdrawal' : IDL.Func([WithdrawalRequest], [IDL.Nat], []),
    'updateWithdrawalStatus' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };