/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const RequestStatus = IDL.Variant({
  'pending' : IDL.Null,
  'paid' : IDL.Null,
  'rejected' : IDL.Null,
});
export const WithdrawalRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : RequestStatus,
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'timestamp' : IDL.Int,
  'upiId' : IDL.Text,
  'contactNo' : IDL.Text,
  'pointsAmount' : IDL.Nat,
  'qrCode' : IDL.Opt(IDL.Vec(IDL.Nat8)),
});
export const WithdrawalRequestInput = IDL.Record({
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'upiId' : IDL.Text,
  'contactNo' : IDL.Text,
  'pointsAmount' : IDL.Nat,
  'qrCode' : IDL.Opt(IDL.Vec(IDL.Nat8)),
});
export const UpdateStatusInput = IDL.Record({
  'id' : IDL.Nat,
  'status' : RequestStatus,
});

export const idlService = IDL.Service({
  'getAllWithdrawalRequests' : IDL.Func(
      [],
      [IDL.Vec(WithdrawalRequest)],
      ['query'],
    ),
  'getWithdrawalRequest' : IDL.Func([IDL.Nat], [WithdrawalRequest], ['query']),
  'submitWithdrawalRequest' : IDL.Func([WithdrawalRequestInput], [IDL.Nat], []),
  'updateRequestStatus' : IDL.Func([UpdateStatusInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const RequestStatus = IDL.Variant({
    'pending' : IDL.Null,
    'paid' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const WithdrawalRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : RequestStatus,
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'timestamp' : IDL.Int,
    'upiId' : IDL.Text,
    'contactNo' : IDL.Text,
    'pointsAmount' : IDL.Nat,
    'qrCode' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  });
  const WithdrawalRequestInput = IDL.Record({
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'upiId' : IDL.Text,
    'contactNo' : IDL.Text,
    'pointsAmount' : IDL.Nat,
    'qrCode' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  });
  const UpdateStatusInput = IDL.Record({
    'id' : IDL.Nat,
    'status' : RequestStatus,
  });
  
  return IDL.Service({
    'getAllWithdrawalRequests' : IDL.Func(
        [],
        [IDL.Vec(WithdrawalRequest)],
        ['query'],
      ),
    'getWithdrawalRequest' : IDL.Func(
        [IDL.Nat],
        [WithdrawalRequest],
        ['query'],
      ),
    'submitWithdrawalRequest' : IDL.Func(
        [WithdrawalRequestInput],
        [IDL.Nat],
        [],
      ),
    'updateRequestStatus' : IDL.Func([UpdateStatusInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };