/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface WithdrawalRequestInput {
    fullName: string;
    email: string;
    address: string;
    upiId: string;
    contactNo: string;
    pointsAmount: bigint;
    qrCode?: Uint8Array;
}
export interface WithdrawalRequest {
    id: bigint;
    status: RequestStatus;
    fullName: string;
    email: string;
    address: string;
    timestamp: bigint;
    upiId: string;
    contactNo: string;
    pointsAmount: bigint;
    qrCode?: Uint8Array;
}
export interface UpdateStatusInput {
    id: bigint;
    status: RequestStatus;
}
export enum RequestStatus {
    pending = "pending",
    paid = "paid",
    rejected = "rejected"
}
export interface backendInterface {
    getAllWithdrawalRequests(): Promise<Array<WithdrawalRequest>>;
    getWithdrawalRequest(id: bigint): Promise<WithdrawalRequest>;
    submitWithdrawalRequest(input: WithdrawalRequestInput): Promise<bigint>;
    updateRequestStatus(input: UpdateStatusInput): Promise<void>;
}
import type { RequestStatus as _RequestStatus, UpdateStatusInput as _UpdateStatusInput, WithdrawalRequest as _WithdrawalRequest, WithdrawalRequestInput as _WithdrawalRequestInput } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getAllWithdrawalRequests(): Promise<Array<WithdrawalRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllWithdrawalRequests();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllWithdrawalRequests();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWithdrawalRequest(arg0: bigint): Promise<WithdrawalRequest> {
        if (this.processError) {
            try {
                const result = await this.actor.getWithdrawalRequest(arg0);
                return from_candid_WithdrawalRequest_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWithdrawalRequest(arg0);
            return from_candid_WithdrawalRequest_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitWithdrawalRequest(arg0: WithdrawalRequestInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitWithdrawalRequest(to_candid_WithdrawalRequestInput_n7(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitWithdrawalRequest(to_candid_WithdrawalRequestInput_n7(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateRequestStatus(arg0: UpdateStatusInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRequestStatus(to_candid_UpdateStatusInput_n9(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRequestStatus(to_candid_UpdateStatusInput_n9(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_RequestStatus_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RequestStatus): RequestStatus {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_WithdrawalRequest_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WithdrawalRequest): WithdrawalRequest {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Uint8Array]): Uint8Array | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _RequestStatus;
    fullName: string;
    email: string;
    address: string;
    timestamp: bigint;
    upiId: string;
    contactNo: string;
    pointsAmount: bigint;
    qrCode: [] | [Uint8Array];
}): {
    id: bigint;
    status: RequestStatus;
    fullName: string;
    email: string;
    address: string;
    timestamp: bigint;
    upiId: string;
    contactNo: string;
    pointsAmount: bigint;
    qrCode?: Uint8Array;
} {
    return {
        id: value.id,
        status: from_candid_RequestStatus_n4(_uploadFile, _downloadFile, value.status),
        fullName: value.fullName,
        email: value.email,
        address: value.address,
        timestamp: value.timestamp,
        upiId: value.upiId,
        contactNo: value.contactNo,
        pointsAmount: value.pointsAmount,
        qrCode: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.qrCode))
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    paid: null;
} | {
    rejected: null;
}): RequestStatus {
    return "pending" in value ? RequestStatus.pending : "paid" in value ? RequestStatus.paid : "rejected" in value ? RequestStatus.rejected : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WithdrawalRequest>): Array<WithdrawalRequest> {
    return value.map((x)=>from_candid_WithdrawalRequest_n2(_uploadFile, _downloadFile, x));
}
function to_candid_RequestStatus_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RequestStatus): _RequestStatus {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateStatusInput_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateStatusInput): _UpdateStatusInput {
    return to_candid_record_n10(_uploadFile, _downloadFile, value);
}
function to_candid_WithdrawalRequestInput_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WithdrawalRequestInput): _WithdrawalRequestInput {
    return to_candid_record_n8(_uploadFile, _downloadFile, value);
}
function to_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: RequestStatus;
}): {
    id: bigint;
    status: _RequestStatus;
} {
    return {
        id: value.id,
        status: to_candid_RequestStatus_n11(_uploadFile, _downloadFile, value.status)
    };
}
function to_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fullName: string;
    email: string;
    address: string;
    upiId: string;
    contactNo: string;
    pointsAmount: bigint;
    qrCode?: Uint8Array;
}): {
    fullName: string;
    email: string;
    address: string;
    upiId: string;
    contactNo: string;
    pointsAmount: bigint;
    qrCode: [] | [Uint8Array];
} {
    return {
        fullName: value.fullName,
        email: value.email,
        address: value.address,
        upiId: value.upiId,
        contactNo: value.contactNo,
        pointsAmount: value.pointsAmount,
        qrCode: value.qrCode ? candid_some(value.qrCode) : candid_none()
    };
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RequestStatus): {
    pending: null;
} | {
    paid: null;
} | {
    rejected: null;
} {
    return value == RequestStatus.pending ? {
        pending: null
    } : value == RequestStatus.paid ? {
        paid: null
    } : value == RequestStatus.rejected ? {
        rejected: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
